version: '2'
services:
    apex-app:
        image: apex
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://apex-mariadb:3306/apex
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apex-mariadb:
        extends:
            file: mariadb.yml
            service: apex-mariadb
